### ISSUE TITLE
Do you have any idea for this error?

### ISSUE THREAD

**Issue by innerpyg** [PacificBiosciences/MethBat#19]
I would like to proceed with a rare methylation anlaysis workflow using the command below.
```
methbat profile \
--input-prefix prefix_cpg \
--input-regions meth_profile_model.tsv \
--output-region-profile test
```

Then, an error occurs.
```
ERROR methbat] Error while aggregating region statistics: CSV deserialize error: record 1 (line: 8, byte: 22): missing field `chrom`
```
Do you have any idea?
Or am i wrong?

**Comment by holtjma** [comment]
Hi @innerpyg,

That usually indicates that something is malformed in the input regions file.  It seems to indicate line 8 in your file as the culprit.  Did you create this file yourself or modify an existing one?

Matt

**Comment by innerpyg** [comment]
Hi Matt,

I didn't create a region file, I just used the two files I found in your github Data folder.

Thanks
Aron

**Comment by holtjma** [comment]
Hmm that’s odd, we’ve had several users use those files without issue.  I suggest verifying they downloaded correctly (or just redownloading them).  Can you provide a full log file?

Matt

**Comment by innerpyg** [comment]
Sorry, it was nothing special.
I think there was a problem with the download as you said.

Thank you

**Comment by holtjma** [comment]
Glad it was simple!

Matt
