### ISSUE TITLE
data available

### ISSUE THREAD

**Issue by HITzhongyu** [PacificBiosciences/MethBat#3]
Hi

I'd like to inquire whether the input for the program should be 'subread.bam' or a BAM file processed through CCS? And is there any sample data available for testing purposes?

Best 
Zhongyu

**Comment by holtjma** [comment]
Hello,

The input to MethBat is actually the output from [pb-CpG-tools](https://github.com/PacificBiosciences/pb-CpG-tools), and pb-CpG-tools accepts an aligned HiFi bam file as input.  More information on usage is available in the user guide: https://github.com/PacificBiosciences/MethBat/blob/main/docs/user_guide.md#quickstart 

We currently do not have a small test dataset to verify the tool is working.  However, there are publicly available CCS datasets you could use.  Some datasets sequenced on Revio can be found here: https://downloads.pacbcloud.com/public/revio/2022Q4/.  Those datasets include a pre-aligned BAM file, so you would just need to download the file, run pb-CpG-tools to get individual methylation loci, and then MethBat to summarize across the CpG islands.

This is an alpha release tool, so we welcome any suggestions or feedback you may have!

Matt

**Comment by holtjma** [comment]
Closing for now, feel free to re-open if needed.
